feat: Make types more compatible if types are narrowed down
thenativeweb/defekt pull request #326
Opened 2021-07-02 08:45 UTC by dotKuro

This PR aims to make Results with overlapping type generic more compatible. This results in cleaner code in some scenarios.

For example:

I have two functions that return the same kind of `error`. I want to use the `value` of the `result` of function a to proceed with my calculation in function b. If function a fails though I just want to propagate the `error`. For now this had to be done this way:

```typescript
function a(): Result<number, SomeError> { ... }

function b(): Result<string, SomeError> {
  const r = a();
  if (r.hasError()) {
    return error(r.error);
  }
  
  return value(`${r.value}`);
}
```

This can be now done a little bit simpler:
```typescript
function a(): Result<number, SomeError> { ... }

function b(): Result<string, SomeError> {
  const r = a();
  if (r.hasError()) {
    return r;
  }
  
  return value(`${r.value}`);
}
```

The old tests were running all fine after the change. I also added 2 new tests.

2021-07-02 08:51 UTC, goloroden requested changes

2021-07-02 08:51 UTC, goloroden commented on test/unit/ResultTests.ts
> +    test('Results of the same error type match when the type is narrowed down to an error.', async (): Promise<void> => {
Test names should begin with a lowercased verb in 3rd person singular.

2021-07-02 08:51 UTC, goloroden commented on test/unit/ResultTests.ts
> +    test('Results of the same value type match when the type is narrowed down to a value.', async (): Promise<void> => {
Test names should begin with a lowercased verb in 3rd person singular.

2021-07-02 08:51 UTC, goloroden commented on lib/Result.ts
> +interface ResultValue<TValue> extends ResultBase<TValue, Error> {
Shouldn't this be `unknown` here as well instead of `Error`?

2021-07-02 08:58 UTC, dotKuro commented on lib/Result.ts
> +interface ResultValue<TValue> extends ResultBase<TValue, Error> {
`unknown` is a bit of magic to me. It kinda acts like `any` in most situations when it comes to "matching other types". In this scenario it does not though. Using `unknown` here yields following error: `Type 'unknown' does not satisfy the constraint 'Error'.`

And it makes sense: We try to find the least narrow types that matches all possible values that will be injected here, in other word the least strict constraint. And that is exactly error, because earlier we defined `TError extends Error`. How exactly `unknown` knows it is not allowed to match here, I have no idea, but it was a great help. Sometimes the Typescript compiler is really smart.

2021-07-02 08:59 UTC, goloroden commented on lib/Result.ts
> +interface ResultValue<TValue> extends ResultBase<TValue, Error> {
Makes sense, thanks for the explanation 👍

2021-07-02 10:13 UTC, strangedev requested changes

2021-07-02 12:02 UTC, goloroden requested changes

2021-07-02 12:02 UTC, goloroden commented on package.json
> -  "dependencies": {},
Please don't remove this line, as keeping this line ensures that *if* one day we have actual dependencies, they get inserted at the right position.

2021-07-02 12:09 UTC, dotKuro commented on package.json
> -  "dependencies": {},
I think that happened automatically, when using `npm install -D`. We will add the line back. Thanks! :)

2021-07-02 12:10 UTC, goloroden commented on package.json
> -  "dependencies": {},
Thanks as well 😊

2021-07-02 12:30 UTC, yeldiRium requested changes
Looks good to me except for some very minor typos :+1: I like the change a lot. Let's see how it holds up in practice.

2021-07-02 12:30 UTC, yeldiRium commented on test/unit/ResultTests.ts
> +  test('should be assignable to an result with the same error type if the result is known to be an error.', async (): Promise<void> => {
```suggestion
  test('should be assignable to a result with the same error type if the result is known to be an error.', async (): Promise<void> => {
```

2021-07-02 12:30 UTC, yeldiRium commented on test/unit/ResultTests.ts
> +  test('should be assignable to an result with the same value type if the result is known to be an value.', async (): Promise<void> => {
```suggestion
  test('should be assignable to a result with the same value type if the result is known to be a value.', async (): Promise<void> => {
```

2021-07-02 15:47 UTC, goloroden approved these changes

2021-07-02 16:04 UTC, strangedev approved these changes
:shipit:

2021-07-03 10:08 UTC, yeldiRium approved these changes

2021-07-03 10:09 UTC, merged